name: bukubuku2_petugas2
version: 1.0.0+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.2
  pretty_dio_logger: ^1.3.1
  file_picker: ^3.0.4
  pdf: ^3.10.8
  path_provider: ^2.1.3
  printing: ^5.12.0
  flutter_plugin_android_lifecycle: ^2.0.17
  open_document: ^1.0.6
  dio: 5.4.0
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  date_time_picker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  jwt_decoder: ^2.0.1
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
    - assets/img/
    - assets/fonts/
  uses-material-design: true

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/img/icon.png
  web: 
    image_path: assets/img/icon.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
    generate: true
  windows: 
    image_path: assets/img/icon.png
    generate: true
    icon_size: 48
  macos: 
    image_path: assets/img/icon.png
    generate: true
  ios: true
  min_sdk_android: 21

